// Generated by Supabase (`generate_typescript_types`) for project pavilion-dev.
// Regenerate after schema changes. Feeds the SupabaseRepository (Phase 2).
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      amenities: {
        Row: { active: boolean; avail_label: string; capacity: number; close_hour: number; community_id: string; created_at: string; icon: string; id: string; max_days_ahead: number; name: string; occ_label: string; open_hour: number; rules: string; slot_minutes: number; sort_order: number; sub: string }
        Insert: { active?: boolean; avail_label?: string; capacity?: number; close_hour?: number; community_id: string; created_at?: string; icon?: string; id?: string; max_days_ahead?: number; name: string; occ_label?: string; open_hour?: number; rules?: string; slot_minutes?: number; sort_order?: number; sub?: string }
        Update: { active?: boolean; avail_label?: string; capacity?: number; close_hour?: number; community_id?: string; created_at?: string; icon?: string; id?: string; max_days_ahead?: number; name?: string; occ_label?: string; open_hour?: number; rules?: string; slot_minutes?: number; sort_order?: number; sub?: string }
        Relationships: [
          { foreignKeyName: "amenities_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
        ]
      }
      arc_requests: {
        Row: { approved: boolean; attachments: string[]; community_id: string; conditions: string; created_at: string; decision_note: string; id: string; ref: string; sort_order: number; status: string; status_label: string; steps: Json; title: string; unit_id: string }
        Insert: { approved?: boolean; attachments?: string[]; community_id: string; conditions?: string; created_at?: string; decision_note?: string; id?: string; ref: string; sort_order?: number; status?: string; status_label?: string; steps?: Json; title: string; unit_id: string }
        Update: { approved?: boolean; attachments?: string[]; community_id?: string; conditions?: string; created_at?: string; decision_note?: string; id?: string; ref?: string; sort_order?: number; status?: string; status_label?: string; steps?: Json; title?: string; unit_id?: string }
        Relationships: [
          { foreignKeyName: "arc_requests_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
          { foreignKeyName: "arc_requests_unit_id_fkey"; columns: ["unit_id"]; isOneToOne: false; referencedRelation: "units"; referencedColumns: ["id"] },
        ]
      }
      board_messages: {
        Row: { body: string; community_id: string; created_at: string; id: string; photos: string[]; sender_profile_id: string; topic: string | null }
        Insert: { body: string; community_id: string; created_at?: string; id?: string; photos?: string[]; sender_profile_id: string; topic?: string | null }
        Update: { body?: string; community_id?: string; created_at?: string; id?: string; photos?: string[]; sender_profile_id?: string; topic?: string | null }
        Relationships: [
          { foreignKeyName: "board_messages_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
          { foreignKeyName: "board_messages_sender_profile_id_fkey"; columns: ["sender_profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      board_topics: {
        Row: { archived: boolean; community_id: string; created_at: string; id: string; name: string }
        Insert: { archived?: boolean; community_id: string; created_at?: string; id?: string; name: string }
        Update: { archived?: boolean; community_id?: string; created_at?: string; id?: string; name?: string }
        Relationships: [
          { foreignKeyName: "board_topics_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
        ]
      }
      audit_log: {
        Row: { action: string; actor_profile_id: string | null; community_id: string; created_at: string; detail: string; id: string }
        Insert: { action: string; actor_profile_id?: string | null; community_id: string; created_at?: string; detail?: string; id?: string }
        Update: { action?: string; actor_profile_id?: string | null; community_id?: string; created_at?: string; detail?: string; id?: string }
        Relationships: [
          { foreignKeyName: "audit_log_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
          { foreignKeyName: "audit_log_actor_profile_id_fkey"; columns: ["actor_profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      communities: {
        Row: {
          brand: Json
          created_at: string
          id: string
          name: string
          settings: Json
          slug: string
        }
        Insert: {
          brand?: Json
          created_at?: string
          id?: string
          name: string
          settings?: Json
          slug: string
        }
        Update: {
          brand?: Json
          created_at?: string
          id?: string
          name?: string
          settings?: Json
          slug?: string
        }
        Relationships: []
      }
      community_requests: {
        Row: { community_name: string; created_at: string; email: string; homes: number | null; id: string; note: string; profile_id: string; requester_name: string; status: string }
        Insert: { community_name: string; created_at?: string; email: string; homes?: number | null; id?: string; note?: string; profile_id: string; requester_name: string; status?: string }
        Update: { community_name?: string; created_at?: string; email?: string; homes?: number | null; id?: string; note?: string; profile_id?: string; requester_name?: string; status?: string }
        Relationships: []
      }
      decisions: {
        Row: { community_id: string; created_at: string; date_label: string; id: string; passed: boolean; pill_label: string; sort_order: number; text: string }
        Insert: { community_id: string; created_at?: string; date_label: string; id?: string; passed?: boolean; pill_label?: string; sort_order?: number; text: string }
        Update: { community_id?: string; created_at?: string; date_label?: string; id?: string; passed?: boolean; pill_label?: string; sort_order?: number; text?: string }
        Relationships: [
          { foreignKeyName: "decisions_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
        ]
      }
      dm_messages: {
        Row: { body: string; created_at: string; id: string; photos: string[]; sender_profile_id: string; thread_id: string }
        Insert: { body: string; created_at?: string; id?: string; photos?: string[]; sender_profile_id: string; thread_id: string }
        Update: { body?: string; created_at?: string; id?: string; photos?: string[]; sender_profile_id?: string; thread_id?: string }
        Relationships: [
          { foreignKeyName: "dm_messages_thread_id_fkey"; columns: ["thread_id"]; isOneToOne: false; referencedRelation: "dm_threads"; referencedColumns: ["id"] },
          { foreignKeyName: "dm_messages_sender_profile_id_fkey"; columns: ["sender_profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      dm_reads: {
        Row: { id: string; last_read_at: string; profile_id: string; thread_id: string }
        Insert: { id?: string; last_read_at?: string; profile_id: string; thread_id: string }
        Update: { id?: string; last_read_at?: string; profile_id?: string; thread_id?: string }
        Relationships: [
          { foreignKeyName: "dm_reads_thread_id_fkey"; columns: ["thread_id"]; isOneToOne: false; referencedRelation: "dm_threads"; referencedColumns: ["id"] },
          { foreignKeyName: "dm_reads_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      dm_threads: {
        Row: { a_profile_id: string; b_profile_id: string; community_id: string; created_at: string; id: string }
        Insert: { a_profile_id: string; b_profile_id: string; community_id: string; created_at?: string; id?: string }
        Update: { a_profile_id?: string; b_profile_id?: string; community_id?: string; created_at?: string; id?: string }
        Relationships: [
          { foreignKeyName: "dm_threads_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
          { foreignKeyName: "dm_threads_a_profile_id_fkey"; columns: ["a_profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "dm_threads_b_profile_id_fkey"; columns: ["b_profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      documents: {
        Row: { community_id: string; created_at: string; id: string; name: string; section: string; size_label: string; storage_path: string; updated_label: string }
        Insert: { community_id: string; created_at?: string; id?: string; name: string; section?: string; size_label?: string; storage_path: string; updated_label?: string }
        Update: { community_id?: string; created_at?: string; id?: string; name?: string; section?: string; size_label?: string; storage_path?: string; updated_label?: string }
        Relationships: [
          { foreignKeyName: "documents_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
        ]
      }
      dues_statements: {
        Row: {
          amount_cents: number
          card_btn: string
          card_sub: string
          card_title: string
          community_id: string
          confirmation: string | null
          created_at: string
          id: string
          is_current: boolean
          period: string
          period_label: string
          sort_order: number
          status: string
          status_label: string
          unit_id: string
        }
        Insert: {
          amount_cents: number
          card_btn?: string
          card_sub?: string
          card_title?: string
          community_id: string
          confirmation?: string | null
          created_at?: string
          id?: string
          is_current?: boolean
          period: string
          period_label?: string
          sort_order?: number
          status?: string
          status_label?: string
          unit_id: string
        }
        Update: {
          amount_cents?: number
          card_btn?: string
          card_sub?: string
          card_title?: string
          community_id?: string
          confirmation?: string | null
          created_at?: string
          id?: string
          is_current?: boolean
          period?: string
          period_label?: string
          sort_order?: number
          status?: string
          status_label?: string
          unit_id?: string
        }
        Relationships: [
          { foreignKeyName: "dues_statements_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
          { foreignKeyName: "dues_statements_unit_id_fkey"; columns: ["unit_id"]; isOneToOne: false; referencedRelation: "units"; referencedColumns: ["id"] },
        ]
      }
      invites: {
        Row: { accepted_at: string | null; code: string; community_id: string; created_at: string; email: string; expires_at: string; id: string; invited_by: string | null; role: "resident" | "board"; status: string; unit_label: string }
        Insert: { accepted_at?: string | null; code?: string; community_id: string; created_at?: string; email: string; expires_at?: string; id?: string; invited_by?: string | null; role?: "resident" | "board"; status?: string; unit_label?: string }
        Update: { accepted_at?: string | null; code?: string; community_id?: string; created_at?: string; email?: string; expires_at?: string; id?: string; invited_by?: string | null; role?: "resident" | "board"; status?: string; unit_label?: string }
        Relationships: [
          { foreignKeyName: "invites_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
          { foreignKeyName: "invites_invited_by_fkey"; columns: ["invited_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      events: {
        Row: { community_id: string; created_at: string; featured: boolean; going: number; id: string; photo_label: string; sort_order: number; tag_label: string; title: string; when_label: string; where_label: string }
        Insert: { community_id: string; created_at?: string; featured?: boolean; going?: number; id?: string; photo_label?: string; sort_order?: number; tag_label?: string; title: string; when_label?: string; where_label?: string }
        Update: { community_id?: string; created_at?: string; featured?: boolean; going?: number; id?: string; photo_label?: string; sort_order?: number; tag_label?: string; title?: string; when_label?: string; where_label?: string }
        Relationships: [
          { foreignKeyName: "events_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
        ]
      }
      event_rsvps: {
        Row: { created_at: string; event_id: string; id: string; profile_id: string }
        Insert: { created_at?: string; event_id: string; id?: string; profile_id: string }
        Update: { created_at?: string; event_id?: string; id?: string; profile_id?: string }
        Relationships: [
          { foreignKeyName: "event_rsvps_event_id_fkey"; columns: ["event_id"]; isOneToOne: false; referencedRelation: "events"; referencedColumns: ["id"] },
          { foreignKeyName: "event_rsvps_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      feed_posts: {
        Row: { author_color: string; author_initial: string; author_name: string; author_profile_id: string | null; body: string; community_id: string; created_at: string; id: string; kind: string; photo_label: string; photos: string[]; pinned: boolean; sort_order: number; tag_label: string; time_label: string; unit_label: string }
        Insert: { author_color?: string; author_initial?: string; author_name: string; author_profile_id?: string | null; body?: string; community_id: string; created_at?: string; id?: string; kind?: string; photo_label?: string; photos?: string[]; pinned?: boolean; sort_order?: number; tag_label?: string; time_label?: string; unit_label?: string }
        Update: { author_color?: string; author_initial?: string; author_name?: string; author_profile_id?: string | null; body?: string; community_id?: string; created_at?: string; id?: string; kind?: string; photo_label?: string; photos?: string[]; pinned?: boolean; sort_order?: number; tag_label?: string; time_label?: string; unit_label?: string }
        Relationships: [
          { foreignKeyName: "feed_posts_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
        ]
      }
      group_event_rsvps: {
        Row: { created_at: string; event_id: string; id: string; profile_id: string }
        Insert: { created_at?: string; event_id: string; id?: string; profile_id: string }
        Update: { created_at?: string; event_id?: string; id?: string; profile_id?: string }
        Relationships: [
          { foreignKeyName: "group_event_rsvps_event_id_fkey"; columns: ["event_id"]; isOneToOne: false; referencedRelation: "group_events"; referencedColumns: ["id"] },
          { foreignKeyName: "group_event_rsvps_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      group_events: {
        Row: { created_at: string; going: number; group_id: string; id: string; title: string; when_label: string; where_label: string }
        Insert: { created_at?: string; going?: number; group_id: string; id?: string; title: string; when_label?: string; where_label?: string }
        Update: { created_at?: string; going?: number; group_id?: string; id?: string; title?: string; when_label?: string; where_label?: string }
        Relationships: [
          { foreignKeyName: "group_events_group_id_fkey"; columns: ["group_id"]; isOneToOne: false; referencedRelation: "groups"; referencedColumns: ["id"] },
        ]
      }
      group_members: {
        Row: { created_at: string; group_id: string; id: string; profile_id: string }
        Insert: { created_at?: string; group_id: string; id?: string; profile_id: string }
        Update: { created_at?: string; group_id?: string; id?: string; profile_id?: string }
        Relationships: [
          { foreignKeyName: "group_members_group_id_fkey"; columns: ["group_id"]; isOneToOne: false; referencedRelation: "groups"; referencedColumns: ["id"] },
          { foreignKeyName: "group_members_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      group_messages: {
        Row: { body: string; created_at: string; group_id: string; id: string; photos: string[]; profile_id: string | null }
        Insert: { body: string; created_at?: string; group_id: string; id?: string; photos?: string[]; profile_id?: string | null }
        Update: { body?: string; created_at?: string; group_id?: string; id?: string; photos?: string[]; profile_id?: string | null }
        Relationships: [
          { foreignKeyName: "group_messages_group_id_fkey"; columns: ["group_id"]; isOneToOne: false; referencedRelation: "groups"; referencedColumns: ["id"] },
          { foreignKeyName: "group_messages_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      group_mutes: {
        Row: { created_at: string; group_id: string; id: string; profile_id: string }
        Insert: { created_at?: string; group_id: string; id?: string; profile_id: string }
        Update: { created_at?: string; group_id?: string; id?: string; profile_id?: string }
        Relationships: [
          { foreignKeyName: "group_mutes_group_id_fkey"; columns: ["group_id"]; isOneToOne: false; referencedRelation: "groups"; referencedColumns: ["id"] },
          { foreignKeyName: "group_mutes_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      group_pins: {
        Row: { author: string; body: string; created_at: string; group_id: string; id: string }
        Insert: { author?: string; body: string; created_at?: string; group_id: string; id?: string }
        Update: { author?: string; body?: string; created_at?: string; group_id?: string; id?: string }
        Relationships: [
          { foreignKeyName: "group_pins_group_id_fkey"; columns: ["group_id"]; isOneToOne: false; referencedRelation: "groups"; referencedColumns: ["id"] },
        ]
      }
      group_poll_votes: {
        Row: { created_at: string; id: string; option: string; poll_id: string; profile_id: string }
        Insert: { created_at?: string; id?: string; option: string; poll_id: string; profile_id: string }
        Update: { created_at?: string; id?: string; option?: string; poll_id?: string; profile_id?: string }
        Relationships: [
          { foreignKeyName: "group_poll_votes_poll_id_fkey"; columns: ["poll_id"]; isOneToOne: false; referencedRelation: "group_polls"; referencedColumns: ["id"] },
          { foreignKeyName: "group_poll_votes_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      group_polls: {
        Row: { author: string; created_at: string; group_id: string; id: string; options: Json; question: string }
        Insert: { author?: string; created_at?: string; group_id: string; id?: string; options?: Json; question: string }
        Update: { author?: string; created_at?: string; group_id?: string; id?: string; options?: Json; question?: string }
        Relationships: [
          { foreignKeyName: "group_polls_group_id_fkey"; columns: ["group_id"]; isOneToOne: false; referencedRelation: "groups"; referencedColumns: ["id"] },
        ]
      }
      groups: {
        Row: { archived: boolean; color: string; community_id: string; created_at: string; created_by: string | null; description: string; icon: string; id: string; is_group_chat: boolean; member_count: number; name: string }
        Insert: { archived?: boolean; color?: string; community_id: string; created_at?: string; created_by?: string | null; description?: string; icon?: string; id?: string; is_group_chat?: boolean; member_count?: number; name: string }
        Update: { archived?: boolean; color?: string; community_id?: string; created_at?: string; created_by?: string | null; description?: string; icon?: string; id?: string; is_group_chat?: boolean; member_count?: number; name?: string }
        Relationships: [
          { foreignKeyName: "groups_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
        ]
      }
      memberships: {
        Row: {
          community_id: string
          created_at: string
          id: string
          profile_id: string
          role: Database["public"]["Enums"]["member_role"]
          status: string
          unit_id: string | null
        }
        Insert: {
          community_id: string
          created_at?: string
          id?: string
          profile_id: string
          role?: Database["public"]["Enums"]["member_role"]
          status?: string
          unit_id?: string | null
        }
        Update: {
          community_id?: string
          created_at?: string
          id?: string
          profile_id?: string
          role?: Database["public"]["Enums"]["member_role"]
          status?: string
          unit_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "memberships_community_id_fkey"
            columns: ["community_id"]
            isOneToOne: false
            referencedRelation: "communities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "memberships_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "memberships_unit_id_fkey"
            columns: ["unit_id"]
            isOneToOne: false
            referencedRelation: "units"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: { avatar_url: string | null; color: string; created_at: string; hide_directory: boolean; id: string; initial: string; name: string; onboarded_at: string | null; phone: string; user_id: string | null }
        Insert: { avatar_url?: string | null; color?: string; created_at?: string; hide_directory?: boolean; id?: string; initial?: string; name: string; onboarded_at?: string | null; phone?: string; user_id?: string | null }
        Update: { avatar_url?: string | null; color?: string; created_at?: string; hide_directory?: boolean; id?: string; initial?: string; name?: string; onboarded_at?: string | null; phone?: string; user_id?: string | null }
        Relationships: []
      }
      post_comments: {
        Row: { author_profile_id: string | null; body: string; created_at: string; id: string; post_id: string }
        Insert: { author_profile_id?: string | null; body: string; created_at?: string; id?: string; post_id: string }
        Update: { author_profile_id?: string | null; body?: string; created_at?: string; id?: string; post_id?: string }
        Relationships: [
          { foreignKeyName: "post_comments_post_id_fkey"; columns: ["post_id"]; isOneToOne: false; referencedRelation: "feed_posts"; referencedColumns: ["id"] },
          { foreignKeyName: "post_comments_author_profile_id_fkey"; columns: ["author_profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      post_reactions: {
        Row: { created_at: string; id: string; post_id: string; profile_id: string }
        Insert: { created_at?: string; id?: string; post_id: string; profile_id: string }
        Update: { created_at?: string; id?: string; post_id?: string; profile_id?: string }
        Relationships: [
          { foreignKeyName: "post_reactions_post_id_fkey"; columns: ["post_id"]; isOneToOne: false; referencedRelation: "feed_posts"; referencedColumns: ["id"] },
          { foreignKeyName: "post_reactions_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      meetings: {
        Row: { agenda: Json; community_id: string; created_at: string; id: string; minutes_path: string | null; status: string; title: string; when_label: string; where_label: string }
        Insert: { agenda?: Json; community_id: string; created_at?: string; id?: string; minutes_path?: string | null; status?: string; title: string; when_label?: string; where_label?: string }
        Update: { agenda?: Json; community_id?: string; created_at?: string; id?: string; minutes_path?: string | null; status?: string; title?: string; when_label?: string; where_label?: string }
        Relationships: [
          { foreignKeyName: "meetings_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
        ]
      }
      units: {
        Row: {
          community_id: string
          created_at: string
          id: string
          label: string
        }
        Insert: {
          community_id: string
          created_at?: string
          id?: string
          label: string
        }
        Update: {
          community_id?: string
          created_at?: string
          id?: string
          label?: string
        }
        Relationships: [
          {
            foreignKeyName: "units_community_id_fkey"
            columns: ["community_id"]
            isOneToOne: false
            referencedRelation: "communities"
            referencedColumns: ["id"]
          },
        ]
      }
      report_comments: {
        Row: { author_profile_id: string | null; body: string; created_at: string; id: string; report_id: string }
        Insert: { author_profile_id?: string | null; body: string; created_at?: string; id?: string; report_id: string }
        Update: { author_profile_id?: string | null; body?: string; created_at?: string; id?: string; report_id?: string }
        Relationships: [
          { foreignKeyName: "report_comments_report_id_fkey"; columns: ["report_id"]; isOneToOne: false; referencedRelation: "reports"; referencedColumns: ["id"] },
          { foreignKeyName: "report_comments_author_profile_id_fkey"; columns: ["author_profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      reports: {
        Row: { board_notes: string; community_id: string; created_at: string; id: string; kind: string; location: string; photos: string[]; ref: string; reporter_label: string; reporter_profile_id: string | null; status: string; title: string; urgency: string; vendor: string }
        Insert: { board_notes?: string; community_id: string; created_at?: string; id?: string; kind?: string; location?: string; photos?: string[]; ref?: string; reporter_label?: string; reporter_profile_id?: string | null; status?: string; title: string; urgency?: string; vendor?: string }
        Update: { board_notes?: string; community_id?: string; created_at?: string; id?: string; kind?: string; location?: string; photos?: string[]; ref?: string; reporter_label?: string; reporter_profile_id?: string | null; status?: string; title?: string; urgency?: string; vendor?: string }
        Relationships: [
          { foreignKeyName: "reports_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
          { foreignKeyName: "reports_reporter_profile_id_fkey"; columns: ["reporter_profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      reservations: {
        Row: { amenity: string; community_id: string; created_at: string; day_label: string; hours: number; id: string; profile_id: string; slot_label: string; status: string; summary: string }
        Insert: { amenity: string; community_id: string; created_at?: string; day_label: string; hours?: number; id?: string; profile_id: string; slot_label: string; status?: string; summary?: string }
        Update: { amenity?: string; community_id?: string; created_at?: string; day_label?: string; hours?: number; id?: string; profile_id?: string; slot_label?: string; status?: string; summary?: string }
        Relationships: [
          { foreignKeyName: "reservations_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
          { foreignKeyName: "reservations_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      special_assessments: {
        Row: { community_id: string; created_at: string; id: string; status: string; sub: string; title: string; unit_id: string }
        Insert: { community_id: string; created_at?: string; id?: string; status?: string; sub?: string; title: string; unit_id: string }
        Update: { community_id?: string; created_at?: string; id?: string; status?: string; sub?: string; title?: string; unit_id?: string }
        Relationships: [
          { foreignKeyName: "special_assessments_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
          { foreignKeyName: "special_assessments_unit_id_fkey"; columns: ["unit_id"]; isOneToOne: false; referencedRelation: "units"; referencedColumns: ["id"] },
        ]
      }
      violations: {
        Row: { community_id: string; created_at: string; description: string; fine_cents: number; id: string; photos: string[]; severity: string; status: string; sub: string; title: string; unit_id: string }
        Insert: { community_id: string; created_at?: string; description?: string; fine_cents?: number; id?: string; photos?: string[]; severity?: string; status?: string; sub?: string; title: string; unit_id: string }
        Update: { community_id?: string; created_at?: string; description?: string; fine_cents?: number; id?: string; photos?: string[]; severity?: string; status?: string; sub?: string; title?: string; unit_id?: string }
        Relationships: [
          { foreignKeyName: "violations_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
          { foreignKeyName: "violations_unit_id_fkey"; columns: ["unit_id"]; isOneToOne: false; referencedRelation: "units"; referencedColumns: ["id"] },
        ]
      }
      vote_ballots: {
        Row: { choice: string; created_at: string; id: string; option_ids: string[]; profile_id: string; receipt: string; vote_id: string }
        Insert: { choice?: string; created_at?: string; id?: string; option_ids?: string[]; profile_id: string; receipt?: string; vote_id: string }
        Update: { choice?: string; created_at?: string; id?: string; option_ids?: string[]; profile_id?: string; receipt?: string; vote_id?: string }
        Relationships: [
          { foreignKeyName: "vote_ballots_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "vote_ballots_vote_id_fkey"; columns: ["vote_id"]; isOneToOne: false; referencedRelation: "votes"; referencedColumns: ["id"] },
        ]
      }
      vote_options: {
        Row: { id: string; label: string; position: number; tally: number; vote_id: string }
        Insert: { id?: string; label: string; position?: number; tally?: number; vote_id: string }
        Update: { id?: string; label?: string; position?: number; tally?: number; vote_id?: string }
        Relationships: [
          { foreignKeyName: "vote_options_vote_id_fkey"; columns: ["vote_id"]; isOneToOne: false; referencedRelation: "votes"; referencedColumns: ["id"] },
        ]
      }
      votes: {
        Row: {
          closed_at: string | null
          closes_at: string | null
          kind: string
          multi: boolean
          closes_label: string
          community_id: string
          created_at: string
          id: string
          no_count: number
          no_label: string
          quorum_count: number
          quorum_total: number
          receipt: string
          status: string
          subtitle: string
          title: string
          yes_count: number
          yes_label: string
        }
        Insert: {
          closed_at?: string | null
          closes_at?: string | null
          kind?: string
          multi?: boolean
          closes_label?: string
          community_id: string
          created_at?: string
          id?: string
          no_count?: number
          no_label?: string
          quorum_count?: number
          quorum_total?: number
          receipt?: string
          status?: string
          subtitle?: string
          title: string
          yes_count?: number
          yes_label?: string
        }
        Update: {
          closed_at?: string | null
          closes_at?: string | null
          kind?: string
          multi?: boolean
          closes_label?: string
          community_id?: string
          created_at?: string
          id?: string
          no_count?: number
          no_label?: string
          quorum_count?: number
          quorum_total?: number
          receipt?: string
          status?: string
          subtitle?: string
          title?: string
          yes_count?: number
          yes_label?: string
        }
        Relationships: [
          { foreignKeyName: "votes_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      claim_invite: { Args: Record<PropertyKey, never>; Returns: boolean }
      claim_invite_code: { Args: { invite_code: string }; Returns: boolean }
      peek_invite: { Args: { invite_code: string }; Returns: { community_name: string; inviter_name: string; role: string; unit_label: string; email: string; state: string }[] }
    }
    Enums: {
      member_role: "resident" | "board"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export const Constants = {
  public: {
    Enums: {
      member_role: ["resident", "board"],
    },
  },
} as const
