// Generated by Supabase (`generate_typescript_types`) for project pavilion-dev.
// Regenerate after schema changes. Feeds the SupabaseRepository (Phase 2).
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      communities: {
        Row: {
          brand: Json
          created_at: string
          id: string
          name: string
          settings: Json
          slug: string
        }
        Insert: {
          brand?: Json
          created_at?: string
          id?: string
          name: string
          settings?: Json
          slug: string
        }
        Update: {
          brand?: Json
          created_at?: string
          id?: string
          name?: string
          settings?: Json
          slug?: string
        }
        Relationships: []
      }
      dues_statements: {
        Row: {
          amount_cents: number
          card_btn: string
          card_sub: string
          card_title: string
          community_id: string
          confirmation: string | null
          created_at: string
          id: string
          is_current: boolean
          period: string
          period_label: string
          sort_order: number
          status: string
          status_label: string
          unit_id: string
        }
        Insert: {
          amount_cents: number
          card_btn?: string
          card_sub?: string
          card_title?: string
          community_id: string
          confirmation?: string | null
          created_at?: string
          id?: string
          is_current?: boolean
          period: string
          period_label?: string
          sort_order?: number
          status?: string
          status_label?: string
          unit_id: string
        }
        Update: {
          amount_cents?: number
          card_btn?: string
          card_sub?: string
          card_title?: string
          community_id?: string
          confirmation?: string | null
          created_at?: string
          id?: string
          is_current?: boolean
          period?: string
          period_label?: string
          sort_order?: number
          status?: string
          status_label?: string
          unit_id?: string
        }
        Relationships: [
          { foreignKeyName: "dues_statements_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
          { foreignKeyName: "dues_statements_unit_id_fkey"; columns: ["unit_id"]; isOneToOne: false; referencedRelation: "units"; referencedColumns: ["id"] },
        ]
      }
      group_event_rsvps: {
        Row: { created_at: string; event_id: string; id: string; profile_id: string }
        Insert: { created_at?: string; event_id: string; id?: string; profile_id: string }
        Update: { created_at?: string; event_id?: string; id?: string; profile_id?: string }
        Relationships: [
          { foreignKeyName: "group_event_rsvps_event_id_fkey"; columns: ["event_id"]; isOneToOne: false; referencedRelation: "group_events"; referencedColumns: ["id"] },
          { foreignKeyName: "group_event_rsvps_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      group_events: {
        Row: { created_at: string; going: number; group_id: string; id: string; title: string; when_label: string; where_label: string }
        Insert: { created_at?: string; going?: number; group_id: string; id?: string; title: string; when_label?: string; where_label?: string }
        Update: { created_at?: string; going?: number; group_id?: string; id?: string; title?: string; when_label?: string; where_label?: string }
        Relationships: [
          { foreignKeyName: "group_events_group_id_fkey"; columns: ["group_id"]; isOneToOne: false; referencedRelation: "groups"; referencedColumns: ["id"] },
        ]
      }
      group_members: {
        Row: { created_at: string; group_id: string; id: string; profile_id: string }
        Insert: { created_at?: string; group_id: string; id?: string; profile_id: string }
        Update: { created_at?: string; group_id?: string; id?: string; profile_id?: string }
        Relationships: [
          { foreignKeyName: "group_members_group_id_fkey"; columns: ["group_id"]; isOneToOne: false; referencedRelation: "groups"; referencedColumns: ["id"] },
          { foreignKeyName: "group_members_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      group_messages: {
        Row: { body: string; created_at: string; group_id: string; id: string; profile_id: string | null }
        Insert: { body: string; created_at?: string; group_id: string; id?: string; profile_id?: string | null }
        Update: { body?: string; created_at?: string; group_id?: string; id?: string; profile_id?: string | null }
        Relationships: [
          { foreignKeyName: "group_messages_group_id_fkey"; columns: ["group_id"]; isOneToOne: false; referencedRelation: "groups"; referencedColumns: ["id"] },
          { foreignKeyName: "group_messages_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      group_mutes: {
        Row: { created_at: string; group_id: string; id: string; profile_id: string }
        Insert: { created_at?: string; group_id: string; id?: string; profile_id: string }
        Update: { created_at?: string; group_id?: string; id?: string; profile_id?: string }
        Relationships: [
          { foreignKeyName: "group_mutes_group_id_fkey"; columns: ["group_id"]; isOneToOne: false; referencedRelation: "groups"; referencedColumns: ["id"] },
          { foreignKeyName: "group_mutes_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      group_pins: {
        Row: { author: string; body: string; created_at: string; group_id: string; id: string }
        Insert: { author?: string; body: string; created_at?: string; group_id: string; id?: string }
        Update: { author?: string; body?: string; created_at?: string; group_id?: string; id?: string }
        Relationships: [
          { foreignKeyName: "group_pins_group_id_fkey"; columns: ["group_id"]; isOneToOne: false; referencedRelation: "groups"; referencedColumns: ["id"] },
        ]
      }
      group_poll_votes: {
        Row: { created_at: string; id: string; option: string; poll_id: string; profile_id: string }
        Insert: { created_at?: string; id?: string; option: string; poll_id: string; profile_id: string }
        Update: { created_at?: string; id?: string; option?: string; poll_id?: string; profile_id?: string }
        Relationships: [
          { foreignKeyName: "group_poll_votes_poll_id_fkey"; columns: ["poll_id"]; isOneToOne: false; referencedRelation: "group_polls"; referencedColumns: ["id"] },
          { foreignKeyName: "group_poll_votes_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      group_polls: {
        Row: { author: string; created_at: string; group_id: string; id: string; options: Json; question: string }
        Insert: { author?: string; created_at?: string; group_id: string; id?: string; options?: Json; question: string }
        Update: { author?: string; created_at?: string; group_id?: string; id?: string; options?: Json; question?: string }
        Relationships: [
          { foreignKeyName: "group_polls_group_id_fkey"; columns: ["group_id"]; isOneToOne: false; referencedRelation: "groups"; referencedColumns: ["id"] },
        ]
      }
      groups: {
        Row: { color: string; community_id: string; created_at: string; description: string; icon: string; id: string; is_group_chat: boolean; member_count: number; name: string }
        Insert: { color?: string; community_id: string; created_at?: string; description?: string; icon?: string; id?: string; is_group_chat?: boolean; member_count?: number; name: string }
        Update: { color?: string; community_id?: string; created_at?: string; description?: string; icon?: string; id?: string; is_group_chat?: boolean; member_count?: number; name?: string }
        Relationships: [
          { foreignKeyName: "groups_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
        ]
      }
      memberships: {
        Row: {
          community_id: string
          created_at: string
          id: string
          profile_id: string
          role: Database["public"]["Enums"]["member_role"]
          status: string
          unit_id: string | null
        }
        Insert: {
          community_id: string
          created_at?: string
          id?: string
          profile_id: string
          role?: Database["public"]["Enums"]["member_role"]
          status?: string
          unit_id?: string | null
        }
        Update: {
          community_id?: string
          created_at?: string
          id?: string
          profile_id?: string
          role?: Database["public"]["Enums"]["member_role"]
          status?: string
          unit_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "memberships_community_id_fkey"
            columns: ["community_id"]
            isOneToOne: false
            referencedRelation: "communities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "memberships_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "memberships_unit_id_fkey"
            columns: ["unit_id"]
            isOneToOne: false
            referencedRelation: "units"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          color: string
          created_at: string
          id: string
          initial: string
          name: string
          user_id: string | null
        }
        Insert: {
          avatar_url?: string | null
          color?: string
          created_at?: string
          id?: string
          initial?: string
          name: string
          user_id?: string | null
        }
        Update: {
          avatar_url?: string | null
          color?: string
          created_at?: string
          id?: string
          initial?: string
          name?: string
          user_id?: string | null
        }
        Relationships: []
      }
      units: {
        Row: {
          community_id: string
          created_at: string
          id: string
          label: string
        }
        Insert: {
          community_id: string
          created_at?: string
          id?: string
          label: string
        }
        Update: {
          community_id?: string
          created_at?: string
          id?: string
          label?: string
        }
        Relationships: [
          {
            foreignKeyName: "units_community_id_fkey"
            columns: ["community_id"]
            isOneToOne: false
            referencedRelation: "communities"
            referencedColumns: ["id"]
          },
        ]
      }
      vote_ballots: {
        Row: { choice: string; created_at: string; id: string; profile_id: string; vote_id: string }
        Insert: { choice: string; created_at?: string; id?: string; profile_id: string; vote_id: string }
        Update: { choice?: string; created_at?: string; id?: string; profile_id?: string; vote_id?: string }
        Relationships: [
          { foreignKeyName: "vote_ballots_profile_id_fkey"; columns: ["profile_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "vote_ballots_vote_id_fkey"; columns: ["vote_id"]; isOneToOne: false; referencedRelation: "votes"; referencedColumns: ["id"] },
        ]
      }
      votes: {
        Row: {
          closes_label: string
          community_id: string
          created_at: string
          id: string
          no_count: number
          no_label: string
          quorum_count: number
          quorum_total: number
          receipt: string
          status: string
          subtitle: string
          title: string
          yes_count: number
          yes_label: string
        }
        Insert: {
          closes_label?: string
          community_id: string
          created_at?: string
          id?: string
          no_count?: number
          no_label?: string
          quorum_count?: number
          quorum_total?: number
          receipt?: string
          status?: string
          subtitle?: string
          title: string
          yes_count?: number
          yes_label?: string
        }
        Update: {
          closes_label?: string
          community_id?: string
          created_at?: string
          id?: string
          no_count?: number
          no_label?: string
          quorum_count?: number
          quorum_total?: number
          receipt?: string
          status?: string
          subtitle?: string
          title?: string
          yes_count?: number
          yes_label?: string
        }
        Relationships: [
          { foreignKeyName: "votes_community_id_fkey"; columns: ["community_id"]; isOneToOne: false; referencedRelation: "communities"; referencedColumns: ["id"] },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      member_role: "resident" | "board"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export const Constants = {
  public: {
    Enums: {
      member_role: ["resident", "board"],
    },
  },
} as const
