import type { Icon, IconWeight } from '@phosphor-icons/react';
import {
  ArrowLeft,
  ArrowsClockwise,
  ArrowUpRight,
  Baby,
  BabyCarriage,
  Bank,
  BatteryFull,
  Bell,
  BellSlash,
  Binoculars,
  BookOpen,
  BookOpenText,
  Broadcast,
  Buildings,
  CalendarBlank,
  CalendarCheck,
  CalendarDots,
  CalendarPlus,
  Camera,
  CameraPlus,
  Car,
  CaretDown,
  CaretRight,
  CaretUp,
  CellSignalFull,
  ChartLineUp,
  ChartPieSlice,
  ChatCircle,
  ChatsCircle,
  ChatTeardropText,
  Check,
  CheckCircle,
  CheckSquare,
  Circle,
  ClockCountdown,
  Dog,
  DotsSixVertical,
  DotsThree,
  EnvelopeSimple,
  Export,
  Eye,
  FileCsv,
  FileMagnifyingGlass,
  Files,
  FileText,
  Gavel,
  GitDiff,
  Hammer,
  HandWaving,
  Heart,
  Hourglass,
  HouseLine,
  IdentificationCard,
  Image,
  Info,
  Invoice,
  Key,
  Lightbulb,
  Lightning,
  LockSimple,
  MagnifyingGlass,
  MapTrifold,
  Mountains,
  Newspaper,
  NotePencil,
  PaperPlaneRight,
  PaperPlaneTilt,
  PawPrint,
  PencilRuler,
  Plant,
  Play,
  Plus,
  Popcorn,
  QrCode,
  Receipt,
  Recycle,
  Scales,
  Scroll,
  SealCheck,
  ShieldCheck,
  ShieldStar,
  SignIn,
  Siren,
  Spade,
  Sparkle,
  Stack,
  Storefront,
  SunHorizon,
  SwimmingPool,
  TennisBall,
  TextAa,
  Ticket,
  Translate,
  Trash,
  Tray,
  User,
  Users,
  UsersFour,
  UsersThree,
  UserSwitch,
  Warning,
  WifiHigh,
  Wrench,
  X,
} from '@phosphor-icons/react';

const ICONS: Record<string, Icon> = {
  'arrow-left': ArrowLeft,
  'arrows-clockwise': ArrowsClockwise,
  'arrow-up-right': ArrowUpRight,
  baby: Baby,
  'baby-carriage': BabyCarriage,
  bank: Bank,
  'battery-full': BatteryFull,
  bell: Bell,
  'bell-slash': BellSlash,
  binoculars: Binoculars,
  'book-open': BookOpen,
  'book-open-text': BookOpenText,
  broadcast: Broadcast,
  buildings: Buildings,
  'calendar-blank': CalendarBlank,
  'calendar-check': CalendarCheck,
  'calendar-dots': CalendarDots,
  'calendar-plus': CalendarPlus,
  camera: Camera,
  'camera-plus': CameraPlus,
  car: Car,
  'caret-down': CaretDown,
  'caret-right': CaretRight,
  'caret-up': CaretUp,
  'cell-signal-full': CellSignalFull,
  'chart-line-up': ChartLineUp,
  'chart-pie-slice': ChartPieSlice,
  'chat-circle': ChatCircle,
  'chats-circle': ChatsCircle,
  'chat-teardrop-text': ChatTeardropText,
  check: Check,
  'check-circle': CheckCircle,
  'check-square': CheckSquare,
  circle: Circle,
  'clock-countdown': ClockCountdown,
  dog: Dog,
  'dots-six-vertical': DotsSixVertical,
  'dots-three': DotsThree,
  'envelope-simple': EnvelopeSimple,
  export: Export,
  eye: Eye,
  'file-csv': FileCsv,
  'file-magnifying-glass': FileMagnifyingGlass,
  files: Files,
  'file-text': FileText,
  gavel: Gavel,
  'git-diff': GitDiff,
  hammer: Hammer,
  'hand-waving': HandWaving,
  heart: Heart,
  hourglass: Hourglass,
  'house-line': HouseLine,
  'identification-card': IdentificationCard,
  'image-square': Image,
  info: Info,
  invoice: Invoice,
  key: Key,
  lightbulb: Lightbulb,
  lightning: Lightning,
  'lock-simple': LockSimple,
  'magnifying-glass': MagnifyingGlass,
  'map-trifold': MapTrifold,
  mountains: Mountains,
  newspaper: Newspaper,
  'note-pencil': NotePencil,
  'paper-plane-right': PaperPlaneRight,
  'paper-plane-tilt': PaperPlaneTilt,
  'paw-print': PawPrint,
  'pencil-ruler': PencilRuler,
  plant: Plant,
  play: Play,
  plus: Plus,
  popcorn: Popcorn,
  'qr-code': QrCode,
  receipt: Receipt,
  recycle: Recycle,
  scales: Scales,
  scroll: Scroll,
  'seal-check': SealCheck,
  'shield-check': ShieldCheck,
  'shield-star': ShieldStar,
  'sign-in': SignIn,
  siren: Siren,
  spade: Spade,
  sparkle: Sparkle,
  stack: Stack,
  storefront: Storefront,
  'sun-horizon': SunHorizon,
  'swimming-pool': SwimmingPool,
  'tennis-ball': TennisBall,
  'text-aa': TextAa,
  ticket: Ticket,
  translate: Translate,
  trash: Trash,
  tray: Tray,
  user: User,
  users: Users,
  'users-four': UsersFour,
  'users-three': UsersThree,
  'user-switch': UserSwitch,
  warning: Warning,
  'wifi-high': WifiHigh,
  wrench: Wrench,
  x: X,
};

export interface PhIconProps {
  name: string;
  size?: number;
  color?: string;
  className?: string;
}

/**
 * Parses prototype-style icon class strings like `"ph-fill ph-swimming-pool"`
 * or `"ph-bold ph-x"` and renders the matching @phosphor-icons/react component.
 * Unknown icon names render nothing.
 */
export function PhIcon({ name, size, color, className }: PhIconProps) {
  const tokens = name.trim().split(/\s+/);
  let weight: IconWeight = 'regular';
  let iconKey: string | undefined;

  for (const token of tokens) {
    if (token === 'ph-fill') weight = 'fill';
    else if (token === 'ph-bold') weight = 'bold';
    else if (token === 'ph') {
      // base prefix, no weight change (defaults to regular unless overridden)
    } else if (token.startsWith('ph-')) {
      iconKey = token.slice(3);
    }
  }

  if (!iconKey) return null;
  const Component = ICONS[iconKey];
  if (!Component) return null;

  return <Component size={size} color={color} weight={weight} className={className} />;
}
